name: Update Language Percentages

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight UTC
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Generate Top Languages SVG
        run: |
          curl -s "https://github-readme-stats.vercel.app/api/top-langs/?username=mhasara&layout=compact&theme=radical&hide_border=true" > languages.svg

      - name: Commit & Push
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "actions@github.com"
          git add languages.svg
          git commit -m "Update language percentages" || echo "No changes to commit"
          git push
